ERROR - 2024-04-16 12:57:28 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:57:28 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:57:41 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:57:41 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:57:58 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:57:58 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:58:34 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:58:34 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:58:50 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:58:50 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:59:12 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:59:12 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 12:59:25 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 12:59:25 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 13:00:30 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('bdlivre.ufrgs.b...', 'find', 'OrweGQRs6rkT', 'find', 3306, '', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in D:\www\find\v2\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\www\find\v2\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\www\find\v2\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#6 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#7 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#8 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-16 13:00:30 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 13:00:58 --> mysqli_sql_exception: Unknown column 'l_name' in 'order clause' in D:\www\find\v2\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\www\find\v2\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-16 13:00:58 --> Unknown column 'l_name' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `library`
ORDER BY `l_name`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `library`
ORDER BY `l_name`')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `library`
ORDER BY `l_name`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 5 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 9 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 13:01:54 --> mysqli_sql_exception: Unknown column 'l_name' in 'order clause' in D:\www\find\v2\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\www\find\v2\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\www\find\v2\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\www\find\v2\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\www\find\v2\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\www\find\v2\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\www\find\v2\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\www\find\v2\app\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
#7 D:\www\find\v2\app\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
#8 D:\www\find\v2\system\CodeIgniter.php(904): App\Controllers\Api->index()
#9 D:\www\find\v2\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\www\find\v2\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\www\find\v2\index.php(70): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-16 13:01:54 --> Unknown column 'l_name' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `library`
ORDER BY `l_name`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `library`
ORDER BY `l_name`')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `library`
ORDER BY `l_name`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `library`
ORDER BY `l_name`', [], false)
 5 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\Find\Library\Index.php(49): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Api.php(13): App\Models\Find\Library\Index->listAll()
 9 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 13:04:02 --> Call to undefined function App\Controllers\get()
in APPPATH\Controllers\Api.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 13:10:10 --> Undefined variable $d1
in APPPATH\Controllers\Api.php on line 17.
 1 APPPATH\Controllers\Api.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $d1', 'APPPATH\\Controllers\\Api.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index('teste')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 13:13:50 --> Call to undefined method App\Controllers\Api::version()
in APPPATH\Controllers\Api.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 13:18:11 --> Attempt to assign property "" on null
in APPPATH\Models\Find\Library\Index.php on line 53.
 1 APPPATH\Controllers\Api.php(19): App\Models\Find\Library\Index->listAll()
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index('library')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 13:18:24 --> Call to undefined function App\Models\Find\Library\pre()
in APPPATH\Models\Find\Library\Index.php on line 55.
 1 APPPATH\Controllers\Api.php(19): App\Models\Find\Library\Index->listAll()
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Api->index('library')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(70): CodeIgniter\CodeIgniter->run()
